# Generated by Django 4.1.1 on 2022-09-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commence', models.DateField()),
                ('firstName', models.CharField(default='', max_length=200)),
                ('surname', models.CharField(default='', max_length=200)),
                ('othernames', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('placeOfBirth', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=200)),
                ('maritalStatus', models.CharField(max_length=200)),
                ('noOfChildren', models.PositiveBigIntegerField()),
                ('religion', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=500)),
                ('nokphone', models.CharField(max_length=500)),
                ('naddress', models.CharField(max_length=500)),
                ('relationship', models.CharField(max_length=500)),
                ('institution1', models.CharField(max_length=500)),
                ('placeAndCountry', models.CharField(max_length=500)),
                ('datefrom', models.CharField(max_length=100)),
                ('certificate1', models.FileField(upload_to='')),
                ('institution2', models.CharField(max_length=500)),
                ('certificate2', models.FileField(upload_to='')),
                ('employername', models.CharField(max_length=500)),
                ('employeraddress', models.CharField(max_length=500)),
                ('appointmentdate', models.CharField(max_length=500)),
                ('salary', models.IntegerField()),
                ('post', models.CharField(max_length=500)),
                ('post2', models.CharField(max_length=500)),
                ('employername2', models.CharField(max_length=500)),
                ('employmentName', models.CharField(max_length=500)),
                ('salary2', models.IntegerField()),
                ('submitdate', models.DateField()),
                ('Signature', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
    ]
