# Generated by Django 4.1.1 on 2022-10-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_application_appointmentdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='session',
            field=models.CharField(choices=[('2022/2023', '2022/2023'), ('2023/2024', '2023/2024')], default='2022/2023', max_length=200),
        ),
    ]
