# Generated by Django 4.1.1 on 2022-10-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_application_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='registration_number',
            field=models.CharField(default='LocGov/2022/3', max_length=250),
        ),
    ]
